# nginx/default.conf

server {
    listen 80;
    server_name localhost; # Hoặc domain của bạn (vd: tungs-web.com)

    location / {
        # 'nextjs_app' là tên service mình sẽ đặt trong docker-compose
        proxy_pass http://nextjs_app:3000;
        
        # Các header cần thiết để Next.js hiểu request gốc
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Cache bypass để hỗ trợ Hot Reload (nếu chạy dev) hoặc WebSocket
        proxy_cache_bypass $http_upgrade;
    }
}
